Sphinx
pedrogabriel69/sof pull request #16
Opened 2017-01-25 16:58 UTC by pedrogabriel69

2017-01-27 07:32 UTC, palkan requested changes

2017-01-27 07:32 UTC, palkan commented on spec/features/search_spec.rb
> +  scenario 'Success, user implements search', js: true do
Please, add specs for all search types.
You should also check the results (not only "no matches" case). Make your tests more meaningful.

Also add a special scenario: searching by full email address.

2017-01-27 22:15 UTC, palkan commented on app/controllers/searches_controller.rb
> +    value = unchecked.include?('@') ? check_spelling(unchecked) : unchecked
Ok, you did it. But it's the only one special symbol that should be escaped, there are some others too.

How do think, maybe, `ThinkingSphinx` has a built-in functionality to escape queries? Have you _googled_ it?

2017-01-28 02:21 UTC, pedrogabriel69 commented on app/controllers/searches_controller.rb
> +    value = unchecked.include?('@') ? check_spelling(unchecked) : unchecked
No) I'll do it

2017-01-28 02:57 UTC, merged